name: CI/CD with CodeQL

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]
   schedule:
      - cron: "30 1 * * 4"

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"
              cache: "yarn"

         - name: Install dependencies
           run: yarn install --frozen-lockfile

         - name: Build application
           run: yarn build

   codeql-analysis:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Initialize CodeQL
           uses: github/codeql-action/init@v3
           with:
              languages: javascript-typescript
              config-file: .github/codeql-config.yml

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"
              cache: "yarn"

         - name: Install dependencies
           run: yarn install --frozen-lockfile

         - name: Perform CodeQL Analysis
           uses: github/codeql-action/analyze@v3

   dependabot:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"
              cache: "yarn"

         - name: Install dependencies
           run: yarn install --frozen-lockfile

         - name: Run build with yarn
           run: yarn build
